version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENABLE_HTTPS=${ENABLE_HTTPS:-false}
    ports:
      - "8000:8000"  # Laravel
      - "5173:5173"  # Vite
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - ./certs:/var/www/certs
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - ENABLE_HTTPS=${ENABLE_HTTPS:-false}
    networks:
      - laravel-vite

networks:
  laravel-vite:
    driver: bridge 