version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ${DOCKER_REGISTRY:-localhost}/cruise-app:${TAG:-latest}
    platform: ${PLATFORM:-linux/amd64}
    ports:
      - "8000:8000"  # Laravel
      - "5173:5173"  # Vite
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - laravel-vite

networks:
  laravel-vite:
    driver: bridge 